spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5434}/${DB_NAME:adso_fincas}
spring.datasource.username=${DB_USER:admin}
spring.datasource.password=${DB_PASSWORD:devbrain_pass}
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.flyway.enabled=false

logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.co.sena.adso.fincasapi=DEBUG

spring.devtools.restart.enabled=true
spring.devtools.restart.poll-interval=2s
spring.devtools.restart.quiet-period=1s
spring.devtools.livereload.enabled=true
spring.devtools.livereload.port=35729
app.security.enabled=false

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.pool-name=FincasAPIDevPool

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

jwt.secret=${JWT_SECRET:dGhpcyBpcyBhIHZlcnkgbG9uZyBzZWNyZXQga2V5IGZvciBKV1QgMjU2IGJpdHMgbWluaW11bQ==}
jwt.expiration=${JWT_EXPIRATION:86400000}
